apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-disk
spec:
  storageClassName: ""
  capacity:
    storage: 25G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: mysql-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volumeclaim
spec:
  storageClassName: ""
  volumeName: mysql-disk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25G