apiVersion: v1
kind: Service
metadata:
  labels:
    app: blog
  name: blog
  namespace: default
spec:
  clusterIP: 10.39.245.12
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 2368
  selector:
    app: blog
  sessionAffinity: None
  type: NodePort